// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

import PlausibleProvider from "next-plausible";
import "./globals.css";

let title = "ihost – AI Code Generator";
let description = "Generate your next dapp with AI Code Generator";
let url = "https://app.sigdao.io/";
// let ogimage = "https://llamacoder.io/og-image.png";
let sitename = "app.sigdao.io";

export const metadata = {
  metadataBase: new URL(url),
  title,
  description,
  icons: {
    icon: "/favicon.ico",
  },
  openGraph: {
    // images: [ogimage],
    title,
    description,
    url: url,
    siteName: sitename,
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    // images: [ogimage],
    title,
    description,
  },
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en" className="h-full">
      <head>
        <PlausibleProvider domain="app.sigdao.io" />
      </head>
      {/* <ChakraProvider theme={theme}>

    <AppContextProvider>
    <ReduxProvider store={store}>
   
    <CoreProvider>
      <UserProvider>
        <GeneratorProvider>
          <WebsiteProvider>
          {isClientSide()
                  ? (<>
                          <AppInitializer/>
                          <Component {...pageProps} />
                      </>
                  )
                  : <Component {...pageProps} />
              }
          </WebsiteProvider>
        </GeneratorProvider>
      </UserProvider>
    </CoreProvider>
    </ReduxProvider>
    </AppContextProvider>
  </ChakraProvider> */}
{children}
    </html>
  );
}
